version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3310:3310"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  app:
    image: cl-app
    container_name: cl-container
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
