version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: spring  # Automatically create the 'spring' database
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  app:
    image: cl
    container_name: cl-container
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/spring
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
